sudo: required
cache: bundler

language: ruby

rvm:
  - 2.5.9
  - 2.6.9
  - 2.7.5

gemfile:
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile
  - gemfiles/rails_6.1.gemfile
  - gemfiles/rails_7.0.gemfile
  - gemfiles/active_record_5.2.gemfile
  - gemfiles/active_record_6.0.gemfile
  - gemfiles/active_record_6.1.gemfile
  - gemfiles/active_record_7.0.gemfile

env:
  - PREPARED_STATEMENTS=0
  - PREPARED_STATEMENTS=1

matrix:
  fast_finish: true
  exclude:
    # Rails7 supports only >= 2.7.0
    - rvm: 2.5.9
      gemfile: gemfiles/rails_7.0.gemfile
    - rvm: 2.5.9
      gemfile: gemfiles/active_record_7.0.gemfile
    - rvm: 2.6.9
      gemfile: gemfiles/rails_7.0.gemfile
    - rvm: 2.6.9
      gemfile: gemfiles/active_record_7.0.gemfile

services:
  - docker

before_install:
  - docker-compose up -d
  - gem install bundler -v 2.1.4

script:
  - bundle exec rake spec
