name: Active Record Multi-Tenant Tests

env:
  CI: true
on:
  push:
    branches:
      - "**"
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  static-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: ruby/setup-ruby@afeafc3d1ab54a631816aba4c914a0081c12ff2f # v1.310.0
        with:
          ruby-version: ruby
          bundler-cache: true
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Rubocop static code analysis
        run: |
          gem install rubocop
          rubocop
  doc_checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4.9.1
        with:
          python-version: 3.9
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install python dependencies
        run: |
          pip install -r docs/requirements.txt
      - name: Documentation Checks
        run: |
          cd docs
          sphinx-build -W -b html source builds

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "3.2"
          - "3.3"
          - "3.4"
          - "4.0"
        appraisal:
          - rails_7.2
          - rails_8.0
          - rails_8.1
          - sidekiq_7_rails_7.2
          - sidekiq_7_rails_8.0
          - sidekiq_7_rails_8.1
        postgresql_version:
          - "14"
          - "15"
          - "16"
    name: Ruby ${{ matrix.ruby }} / ${{ matrix.appraisal }} / PostgreSQL ${{ matrix.postgresql_version }}
    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.appraisal }}.gemfile
      POSTGRES_VERSION: ${{ matrix.postgresql_version }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Start PostgreSQL Database environment
        run: docker compose up -d

      - uses: ruby/setup-ruby@afeafc3d1ab54a631816aba4c914a0081c12ff2f # v1.310.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Execute tests
        run: bundle exec rake spec

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@ab904c41d6ece82784817410c45d8b8c02684457 # v3.1.6
